# Generated by Django 4.0.3 on 2022-03-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valana', '0003_remove_curso_id_alter_curso_camada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='id',
        ),
        migrations.AddField(
            model_name='entregable',
            name='calificacion_minima',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
