# Generated by Django 4.0.3 on 2022-04-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valana', '0006_imagen_imagen_alter_imagen_id_alter_pais_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='imagen',
            new_name='foto',
        ),
    ]
