# Generated by Django 4.0.3 on 2022-04-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valana', '0009_posteo_autor_posteo_imagenposteo_posteo_subtitulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='foto',
            new_name='fotoimagen',
        ),
    ]
