# Generated by Django 4.0.3 on 2022-04-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valana', '0010_rename_foto_foto_fotoimagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='fotoimagen',
            new_name='imagen',
        ),
    ]
